<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Release Payment</description>
   <name>Release Payment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ff90852c-0c94-4ad1-94b7-3e3b74f35e36</testSuiteGuid>
   <testCaseLink>
      <guid>4cb948b2-bd88-4a8e-bc59-e0dcba314386</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.1 Mengakses halaman Release Payment Tab To Do List seharusnya data berstatus DRAFT atau ON PROGRESS tampil</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e964bf0-3a49-4a0f-bc21-8cf5f510c754</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f719b204-166f-4e27-9660-9d7ed1ffe990</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b1e391e-141d-4091-af5b-8b1b1f5bda84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cd8b6c9-d12b-45bc-a595-f77e220c737d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e057075-0dfd-4d5c-b1d2-1b5dcb449034</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f01fb63-7d8b-4c24-b295-02c4b8fbbe38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.2 Mencari data pada Tab To Do List seharusnya data yang dicari berhasil tampil</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34f75b0d-609d-4cb8-8b60-5f8fcd44f608</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5d71cbb-6354-4564-8abb-2007e975349f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac5e8228-7bc2-402f-b51d-00a5b864f9cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93d8b055-99c0-4383-811f-1b148f10e14b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cbdea27-6293-4c4a-adff-e5cb39062499</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4abc5c1f-ef91-4d36-a15f-1939ad9a6864</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.3 -Melihat detail data pada View Tab To Do List seharusnya detail data yang dipilih berhasil tampil</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd7e4a8-614a-4776-b23a-21ceb7341bd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ed20a3d-f9d1-4ea9-8786-5a4078e956b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61fa0607-faba-4881-8023-0aabef20c401</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c24bdcb0-dd2f-4794-b317-847e41f35cec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1b12811-1cb4-441f-aae1-9afe614f412f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>605354b6-e429-47dc-b5a9-eee710b8a1e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.4 Mengakses halaman Tab History seharusnya data yang telah selesai tampil</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6268df2a-6f68-41e2-a604-a46f5548cf8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a21d1a24-23d7-4441-bad5-23243d8f5534</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2b24fa5-1b69-4967-870d-13bd4812fb24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dee7510-c09f-4778-bf10-f2fd0580bf53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8df498d-6e61-4533-895a-b7466685eea9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>033087dd-38a3-4c92-b789-e63e2fde349f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.5 Mencari data pada Tab History seharusnya data yang dicari berhasil tampil</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb60852-5983-4932-af37-0e824e16900a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6593060-5d0d-423f-9458-b126d9332f3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f96f7b00-7009-493d-9e3f-13beee1fad50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da440388-639b-49c4-aa2c-18a3b54eb562</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60d34ed6-45da-40db-b912-947dbd6518fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76afd6b0-f304-4270-a1cd-2b0f42f28d21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.6 Melihat detail data pada View Tab History seharusnya detail data yang dipilih berhasil tampil</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41a0a18d-9d56-4fa1-afcb-8e9234a88f8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91bb18b6-0a76-4ba1-9438-e19059a7a24a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a317831-b7c9-48ff-b5f1-e2d2fa059df1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e346286-4230-4d5a-8742-adc17dac0ba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>755e7077-0423-4ed6-8e77-405fd938dbed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2540bb7-1b85-4299-9fa9-5f7ba57d64a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.8 Membuat Release Payment tanpa Description seharusnya data tidak berhasil di-Submit</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b05f3347-fa9c-4ce1-b353-6b4f0291747f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Release Payment/Release Payment</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b05f3347-fa9c-4ce1-b353-6b4f0291747f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>260f726b-e163-4d94-8e95-1a5f20acbeee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b05f3347-fa9c-4ce1-b353-6b4f0291747f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>b94f6c60-3616-456e-8990-ebb03fb92d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b05f3347-fa9c-4ce1-b353-6b4f0291747f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dateReleased</value>
         <variableId>70174a12-dc4e-4b45-9240-f782214c656c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b05f3347-fa9c-4ce1-b353-6b4f0291747f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Requestor</value>
         <variableId>90d583f9-2969-4aad-aaa5-d17e2dc5f86d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b05f3347-fa9c-4ce1-b353-6b4f0291747f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>0059bf33-5118-46ea-af25-60057566e598</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03f73c66-39d6-4dcb-8978-c84c5a5a3ef7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.7 Membuat Release Payment dengan Tipe Kasbon POA seharusnya data berhasil di-Submit</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>398b4b61-b209-44a0-bcbd-6b1d671c9a92</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Release Payment/Release Payment</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>398b4b61-b209-44a0-bcbd-6b1d671c9a92</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>1ef4703c-a279-4cfa-a27b-3d5d4aac8404</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>398b4b61-b209-44a0-bcbd-6b1d671c9a92</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>6e850733-0629-47b1-902d-be4d09ed58e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>398b4b61-b209-44a0-bcbd-6b1d671c9a92</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dateReleased</value>
         <variableId>bbc776a3-a88f-417d-a23d-66aa43f2a086</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>398b4b61-b209-44a0-bcbd-6b1d671c9a92</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Requestor</value>
         <variableId>f67a173a-1ffd-42ab-8ae9-7492f0d65897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>398b4b61-b209-44a0-bcbd-6b1d671c9a92</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>99f90207-b618-4e85-b00f-3070ccef3fc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>356c3988-d277-4d24-bbbe-e18536fa4cc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/7. Release Payment/7.9 Mencetak Release Payment pada Tab History seharusnya data berhasil dicetak</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a4d47d5-b347-4eb8-a1ef-e72aaee36e22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43f759c3-a3b9-4322-b640-852e3e4136d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca22092c-fc35-4fda-90e1-3aaf4043adf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e181a066-40e5-4da1-b87f-8a38f9488ca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bff6fdb9-865c-494d-a245-4452c4d55ffa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
